version: '2'

volumes:
  adaptdata:
  adaptdb:

services:
  db:
    container_name: adaptdb
    image: mongo
    volumes:
      - adaptdb:/data/db
  authoring:
    container_name: adaptauthoring
    build: .
    image: garyritchie/docker-adaptauthoring:0.2.2
    volumes:
      - adaptdata:/adapt_authoring
    links:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
