version: '2'

volumes:
  adaptdata:
  adaptdb:

services:
  db:
    container_name: adaptdb
    image: mongo
    volumes:
      - adaptdb:/data/db
    # ports:
    #   - 27017:27017
  authoring:
    volumes:
      - adaptdata:/adapt_authoring
    container_name: adaptauthoring
    build: .
    command: pm2 start --no-daemon processes.json
    links:
      - db
    # depends_on:
    #   - db
    ports:
      - "5000:5000"
