version: '2'

volumes:
  adaptdata:
    external:
      name: dockeradaptauthoring_adaptdata

services:
  setup:
    container_name: adaptauthoring
    env_file: .env
    build: .
    image: garyritchie/docker-adaptauthoring:0.2.2
    # extends:
    #   file: docker-compose.yml
    #   service: authoring
    # volumes_from:
    #   - adaptauthoring
    volumes:
      - adaptdata:/adapt_authoring
    external_links:
      - adaptdb
    command: bash ./install.sh
  upgrade:
    extends:
      service: setup
    command: node upgrade --Y/n Y
